[package]
name = "tfhe-rs_practice721"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfhe = { version = "0.2.4", features = [ "boolean", "shortint", "integer"] }
